"""add_activos_fotos_table

Revision ID: b3a1ecbe72df
Revises: cc1398101ac3
Create Date: 2026-06-26 09:43:24.194580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a1ecbe72df'
down_revision: Union[str, Sequence[str], None] = 'cc1398101ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activos_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_activo', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_activo'], ['activos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activos_fotos_id'), 'activos_fotos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activos_fotos_id'), table_name='activos_fotos')
    op.drop_table('activos_fotos')
    # ### end Alembic commands ###
