"""add latitud_longitud to activos

Revision ID: cc1398101ac3
Revises: 5f96ab620aaa
Create Date: 2026-06-26 09:04:49.172708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1398101ac3'
down_revision: Union[str, Sequence[str], None] = '5f96ab620aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activos', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('activos', sa.Column('longitud', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activos', 'longitud')
    op.drop_column('activos', 'latitud')
    # ### end Alembic commands ###
