"""add_fecha_baja_soft_delete

Revision ID: d959963545e2
Revises: d4e5f6a7b8c9
Create Date: 2026-07-03 19:26:46.031192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd959963545e2'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activos', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activos_fotos', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asignaciones_activo', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('categorias_activo', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('checklist_estado', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clientes', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contratos', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('historial_ubicacion', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mantenimientos', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pagos', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reportes_incidencia', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_baja')
    op.drop_column('roles', 'fecha_baja')
    op.drop_column('reportes_incidencia', 'fecha_baja')
    op.drop_column('pagos', 'fecha_baja')
    op.drop_column('mantenimientos', 'fecha_baja')
    op.drop_column('historial_ubicacion', 'fecha_baja')
    op.drop_column('contratos', 'fecha_baja')
    op.drop_column('clientes', 'fecha_baja')
    op.drop_column('checklist_estado', 'fecha_baja')
    op.drop_column('categorias_activo', 'fecha_baja')
    op.drop_column('asignaciones_activo', 'fecha_baja')
    op.drop_column('activos_fotos', 'fecha_baja')
    op.drop_column('activos', 'fecha_baja')
    # ### end Alembic commands ###
