"""add_url_documento_to_contratos

Revision ID: fea5c70ae009
Revises: b3a1ecbe72df
Create Date: 2026-06-27 13:47:29.436557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea5c70ae009'
down_revision: Union[str, Sequence[str], None] = 'b3a1ecbe72df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('url_documento', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'url_documento')
    # ### end Alembic commands ###
